version: '3.8'

services:
  gatekeeper:
    build: ./gatekeeper-docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - zk-artifacts:/shared
    user: "${UID}:${GID}"
    network_mode: "host"
    environment:
      - CESS_GATEWAY=https://deoss-sgp.cess.network
      - CESS_TERRITORY=SOMETHING
      - PUB_KEY=5Cepa34KmHKM7vbq8P8bz5asVFRYtN1KHk3VKpmkvJindNxy
      - MNEMONIC=protect reduce slab market blame foster spread toddler lobster escape forest ozone
      - CYBORG_TEST_KEY=bottom drive obey lake curtain smoke basket hold race lonely fit walk//Alice
      - RPC_URL=wss://testnet-rpc.cess.network/ws/
      - PARACHAIN_URL=${PARACHAIN_URL}
      - DOCKER_HOST=unix:///var/run/docker.sock

  miner:
    build: 
      context: .
      dockerfile: miner-docker/Dockerfile
    volumes:
      - zk-artifacts:/shared
    network_mode: "host"
    environment:
      - LOG_FILE_PATH=miner/logs/miner.log
      - TASK_FILE_NAME=archive.tar.zst
      - TASK_DIR_PATH=/shared
      - IDENTITY_FILE_PATH=miner/config/miner_identity.json
      - TASK_OWNER_FILE_PATH=miner/config/task_owner.json
      - PARACHAIN_URL=${PARACHAIN_URL}
      - UPDATER_LOG_FILE_PATH=miner/logs/updater.log
      - TAILSCALE_NET=tail78ea2b.ts.net
      - CYBORG_MINER_TEST_IP=127.0.0.1
      - FLASH_INFER_PORT=3005
      - CURRENT_TASK_PATH=miner/config/current_task.json
      - MINER_TYPE=${MINER_TYPE}
      - MINER_TMP_DIR=miner/tmp

volumes:
  zk-artifacts:
